### PR TITLE
blogpost yeah

### PR DESCRIPTION
**Pull request by berlintam**
still to do:
* [x] write blogpost
* [x] find sound
* [x] upload pics
* [x] upload podcast
* [ ] write facebook post
* [ ] tweet
* [ ] bask in awesomeness

### CODE REVIEW

**Comment by berlintam** [comment]
potential track https://soundcloud.com/novi/the-direction-of-time

**Comment by bitboxer** [comment]
I am now uploading the audio to auphonic. I used the potential track but sadly I can't figure out a way to combine the images :/ . Code for de has a nice logo,  but the others...thats hard to put them on one image for me. How do we proceed? Do you have an idea?

**Comment by berlintam** [comment]
I think the code for de logo is totally fine.

**Comment by bitboxer** [comment]
Okay, than we use that.

**Comment by bitboxer** [comment]
Added the logo. Will go out and eat something and post the link to the file when I am back!

**Comment by bitboxer** [comment]
Can you check the audio file on soundcloud if it is okay for you?

**Pull request merged**
