### PR TITLE
Fav podcast 2

### PR DESCRIPTION
**Pull request by berlintam**
@bitboxer 

what do you think?
I couldn't find a logo for Wostkinder....

### CODE REVIEW

**Comment by bitboxer** [comment]
We could add that I was part of the Geekstammtisch Podcast on the Congress (if people miss my voice, they have a way to listen to the over sugared and over caffeinated version of that ;) ) here: http://geekstammtisch.de/#GST036

**Comment by bitboxer** [comment]
And sadly wostkinder don't have a logo :( . 

Other than that: :+1:

**Comment by berlintam** [comment]
oh ya! did you want to first release a blogpost about that?

**Comment by bitboxer** [comment]
A full blogpost is not necessary. A sentence in the beginning in this post is enough I think.

**Comment by berlintam** [comment]
k, i'll add that now!

**Comment by berlintam** [comment]
"This year's CCC" or "This year's Congress", or "This year's CCC Congress"?

**Comment by bitboxer** [comment]
"The 31st chaos communication congress" is the most clear one I think. It was last year + CCC  and the Congress have the same 3 letter acronym...just to test the intelligence of everyone :wink:

**Comment by bitboxer** [comment]
Okay, it's online now. I fixed a little typo in the images. And yes, I hate the CCC naming, too :wink: . Totally confusing for everyone. As I said: they did that on purpose :sob: .

**Comment by bitboxer** [comment]
Ah, just realized: we also need to tweet this :smile: .

What do you think of: "We will record a new episode soon. Till then you could listen to one of the podcasts we recommend http://bitsofberlin.org/2015/01/04/podcast-recommendations_2/" . Or do you have something catchier in mind?

**Comment by berlintam** [comment]
Go for it!

**Comment by bitboxer** [comment]
done

**Pull request merged**
