### PR TITLE
episode 10 satellites blogpost

### PR DESCRIPTION
**Pull request by berlintam**
TODO:
* [x] music
* [x] picture
* [x] add podcast
* [ ] release
* [ ] bask in awesomeness

### CODE REVIEW

**Comment by bitboxer** [comment]
Sascha also send us a photo of Kreta. Should I add it to the blogpost?

**Comment by berlintam** [comment]
Sure. I also have a pic of the satellite dish up on the roof, do you want to use that as well?

**Comment by bitboxer** [comment]
All the pics!!!

**Comment by bitboxer** [comment]
@berlintam I added the Photo of Sascha. Can you add the Pic of the dish? They have a reduced quality when I copy them out of signal sadly.

**Comment by bitboxer** [comment]
giphy

**Pull request merged**
